name: Generate contribution animation

on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2373f7bf&color_dots=%23111614,%231d3a30,%2329634d,%234ba97e,%2373f7bf
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%2373f7bf&color_dots=%230b0f0d,%23172922,%23264c3b,%23458d6b,%2373f7bf

      - name: Publish animation to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
